resolver: lts-4.1

packages:
- '.'
- location:
    git: https://github.com/barischj/threepenny-gui
    commit: a676e3364fe1547028540417aad4e92a75fa63b6
  extra-dep: true
- location:
    git: https://github.com/barischj/threepenny-gui-contextmenu
    commit: 03cde41159663fde5c8b11c22e96c4f7dadf30f7
  extra-dep: true

extra-deps:
- aeson-0.11.3.0
- bytestring-builder-0.10.8.1.0
- Cabal-1.22.5.0
# - cabal-install-1.24
- cabal-macosx-0.2.3.4
- clock-0.7.2
- fail-4.9.0.0
- io-streams-haproxy-1.0.0.1
- readable-0.3.1
- snap-core-1.0.1.0
- snap-server-1.0.1.1
- tagged-0.8.4
- unix-compat-0.4.3.1
- websockets-0.9.8.2
- websockets-snap-0.10.2.0
- wx-0.92.2.0
- wxc-0.92.2.0
- wxcore-0.92.2.0
- wxdirect-0.92.2.0

flags: {}

extra-package-dbs: []

explicit-setup-deps:
  '*': true
  entropy: false
