LitSwitch -Ehaskell,verbatim -Ocode -B   EParseLib.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   LaTeXAST.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   LaTeXErrors.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   Utilities.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   Tables.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   Datatypes.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   Invariants.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   Precedences.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   DataText.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   DSL.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   Heuristics.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   LaTeXSetup.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   LaTeXNames.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   LaTeXLexer.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   LaTeXParse.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   Matching.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   FreeBound.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   Focus.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   AlphaSubs.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   Types.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   Manipulation.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   Normalise.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   Proof.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   Theories.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   Builtin.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   Logic.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   FromZ.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   LaTeXPretty.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   LaTeXParserIF.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   LaTeXTest.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   GS3001.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   GSLogic.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   UTP.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   DocTextParser.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   ImportExport.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   Files.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   Archive.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   RAlg.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   R.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   SaoithinTypes.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   SaoithinState.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   SaoithinRender.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   SaoithinProof.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   SaoithinTheory.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   SaoithinFiles.lhs
LitSwitch -Ehaskell,verbatim -Ocode -B   Saoithin.lhs
